/**
 * @author           Shahida K
 * @version          1.0 
 * @date             23/01/2017
 * @Status           Developed
 * @description     test class for EZRE_RecursionCheckforTrigger class                  
 */

@isTest
public class EZRE_RecursionCheckforTrigger_Test
{
    ///OBJECTIVE
    ///Test method to test EZRE_RecursionCheckforTrigger class functionality.                  
    ///OBJECTIVE
    Public static testmethod void checkRecusionFlag()
    {
        EZRE_RecursionCheckforTrigger RecursionCheckforTrigger=new EZRE_RecursionCheckforTrigger();
    }      
}