public class SendChatGPTRecord {
    
    private final String clientId = '3MVG9Iu66FKeHhIP8TMveNZt9ut4wqUvVvQwBhn5HpHmDvsvmm1NSMycpbznmWCFwJW2b8IE_QQFuC3Vnkhxe';
    private final String clientSecret = '97B561E73E07B07C02B5B67C548765B959D2B2D4CC5CCDA6EA0E0329B98FC25A';
    private final String username = 'sfadmin@demandblue.com.innovation.jiraintegr';
    private final String password = 'Prelude@1234';
    

}